# Generated by Django 5.0.6 on 2026-07-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restauranteditrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
