# Generated by Django 5.0.6 on 2026-07-15 14:50

import restaurants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_cuisine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to=restaurants.models.business_license_upload_to),
        ),
    ]
