# Generated by Django 5.0.6 on 2026-07-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_restaurant_business_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_membership_only',
            field=models.BooleanField(default=False),
        ),
    ]
