# Generated by Django 5.0.6 on 2026-07-21 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_menu_is_membership_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantClosedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_dates', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('restaurant', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RestaurantRegularClosedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, '월요일'), (1, '화요일'), (2, '수요일'), (3, '목요일'), (4, '금요일'), (5, '토요일'), (6, '일요일')])),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regular_closed_days', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['weekday'],
                'unique_together': {('restaurant', 'weekday')},
            },
        ),
    ]
