# Generated by Django 5.0.6 on 2026-07-21 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_image'),
        ('restaurants', '0006_restaurantcloseddate_restaurantregularclosedday'),
    ]

    operations = [
    ]
