# Generated by Django 5.0.6 on 2026-07-21 06:22

import restaurants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurantcloseddate_restaurantregularclosedday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=restaurants.models.menu_image_upload_to),
        ),
    ]
