# Generated by Django 5.0.6 on 2026-07-21 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_merge_20260721_1532'),
        ('restaurants', '0008_alter_menu_image'),
    ]

    operations = [
    ]
