# Generated by Django 5.0.6 on 2026-07-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '결제대기'), ('placed', '점주확인대기'), ('accepted', '주문접수'), ('rejected', '주문거절'), ('cooking', '조리중'), ('cooked', '조리완료'), ('delivering', '배달중'), ('delivered', '배달완료'), ('cancelled', '주문취소')], default='pending', max_length=16),
        ),
    ]
