# Generated by Django 5.0.6 on 2026-07-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', '승인 대기'), ('active', 'Active'), ('suspended', 'Suspended'), ('withdrawn', 'Withdrawn')], default='active', max_length=16),
        ),
    ]
