# Generated by Django 5.0.6 on 2026-07-15 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_status'),
        ('accounts', '0002_withdrawalrequest'),
    ]

    operations = [
    ]
