# Generated by Django 5.0.6 on 2026-07-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_rrn_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rrn_hash',
            field=models.CharField(blank=True, help_text='주민등록번호 중복 확인용 해시(SHA-256). 복호화 불가능해서 이 값만으로는 원본을 알 수 없다.', max_length=64, null=True, unique=True),
        ),
    ]
