# Generated by Django 5.0.6 on 2026-07-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_rrn_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rrn_encrypted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rrn_hash',
        ),
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, help_text='계좌번호 암호화 (점주웹, AES-128)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, help_text='은행명 (점주웹)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='card_cvc',
            field=models.CharField(blank=True, help_text='카드 CVC 암호화 (AES-128)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='card_number',
            field=models.CharField(blank=True, help_text='카드번호 암호화 (사용자앱, AES-128)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='card_password_2digit',
            field=models.CharField(blank=True, help_text='카드 비밀번호 2자리 암호화 (AES-128)', max_length=255, null=True),
        ),
    ]
