# Generated by Django 5.0.6 on 2026-07-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_payment_pw_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rrn_encrypted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rrn_hash',
        ),
        migrations.AddField(
            model_name='user',
            name='account_number_encrypted',
            field=models.CharField(blank=True, help_text='계좌번호 (AES-128 암호화). accounts.crypto_utils.encrypt_aes128 으로 저장한다.', max_length=255, null=True),
        ),
    ]
