# Generated by Django 5.0.6 on 2026-07-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_user_rrn_encrypted_remove_user_rrn_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, help_text='은행명 (점주웹)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='card_cvc',
            field=models.CharField(blank=True, help_text='카드 CVC (AES-128 암호화)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='card_number',
            field=models.CharField(blank=True, help_text='카드번호 (AES-128 암호화)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='card_password_2digit',
            field=models.CharField(blank=True, help_text='카드 비밀번호 2자리 (AES-128 암호화)', max_length=255, null=True),
        ),
    ]
