# Generated by Django 5.0.6 on 2026-08-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_bank_name_user_card_cvc_user_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resident_number_encrypted',
            field=models.CharField(blank=True, help_text='주민등록번호 13자리 (AES-128 암호화). 본인확인·정산신고용. 평문 저장 금지.', max_length=255, null=True),
        ),
    ]
