# Generated by Django 5.0.6 on 2026-07-23 06:29

import django.db.models.deletion
import inquiries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='category',
            field=models.CharField(choices=[('order', '주문/결제'), ('delivery', '배달'), ('refund', '환불/교환'), ('coupon', '쿠폰/프로모션'), ('account', '계정'), ('etc', '기타')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='title',
            field=models.CharField(max_length=16),
        ),
        migrations.CreateModel(
            name='InquiryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=inquiries.models.inquiry_image_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inquiries.inquiry')),
            ],
        ),
    ]
