# Generated by Django 5.0.6 on 2026-07-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercoupon',
            unique_together=set(),
        ),
    ]
