# Generated by Django 5.0.6 on 2026-07-20 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_coupon'),
        ('promotions', '0003_restore_usercoupon_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_membership_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MembershipPointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('earn', 'Earn'), ('spend', 'Spend')], default='earn', max_length=8)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('balance_after', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='promotions.membership')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
