# Generated by Django 5.0.6 on 2026-08-20 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_riderlocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=64)),
                ('account_number_encrypted', models.CharField(blank=True, max_length=255, null=True)),
                ('account_holder', models.CharField(blank=True, max_length=64)),
                ('license_number', models.CharField(blank=True, max_length=64)),
                ('vehicle_number', models.CharField(blank=True, max_length=32)),
                ('region', models.CharField(blank=True, max_length=128)),
                ('delivery_method', models.CharField(blank=True, choices=[('walk', '도보'), ('bicycle', '자전거'), ('motorcycle', '오토바이'), ('car', '자동차')], max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
