# Generated by Django 5.0.6 on 2026-08-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0003_riderprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='distance_km',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
