# Generated by Django 5.0.6 on 2026-08-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0004_delivery_distance_km_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
