# Generated by Django 5.0.6 on 2026-08-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0005_delivery_settled_delivery_settled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='start_distance_km',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='riderlocation',
            name='total_distance_km',
            field=models.FloatField(default=0),
        ),
    ]
