# Generated by Django 5.0.6 on 2026-08-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0007_txnnonce_txnkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFeePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fee_krw', models.PositiveIntegerField(default=3000)),
                ('fee_per_km', models.PositiveIntegerField(default=1000)),
                ('max_fee_krw', models.PositiveIntegerField(default=50000)),
            ],
            options={
                'db_table': 'delivery_fee_policy',
            },
        ),
    ]
