# Generated by Django 5.0.6 on 2026-08-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0009_seed_delivery_fee_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='distance_seal',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='delivery',
            name='receipt_proof',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='txnkey',
            name='reg_seal',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
