# Generated by Django 5.0.6 on 2026-08-23 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0010_delivery_distance_seal_delivery_receipt_proof_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='paid_out',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RiderPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('dest_bank_name', models.CharField(blank=True, max_length=64)),
                ('dest_account_masked', models.CharField(blank=True, max_length=64)),
                ('dest_account_holder', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('paid', 'Paid')], default='paid', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
