# Generated by Django 5.0.6 on 2026-07-21 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
        ('restaurants', '0009_merge_0007_merge_20260721_1532_0008_alter_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrequest',
            name='restaurant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_request', to='restaurants.restaurant'),
        ),
    ]
