# Generated by Django 5.0.6 on 2026-07-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_enrollmentrequest_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
