# Generated by Django 5.0.6 on 2026-07-22 05:03

import adminpanel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=adminpanel.models.notice_image_upload_to),
        ),
    ]
