# Generated by Django 5.0.6 on 2026-07-28 02:17

import adminpanel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_metricsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=adminpanel.models.notice_attachment_upload_to),
        ),
    ]
