# Generated by Django 5.0.6 on 2026-07-21 06:23

import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(upload_to=reviews.models.review_image_upload_to),
        ),
    ]
