# Generated by Django 5.0.6 on 2026-07-21 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_rating'),
        ('reviews', '0003_alter_reviewimage_image'),
    ]

    operations = [
    ]
